[2025-05-05T22:43:13.093+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:33:02.097910+00:00 [queued]>
[2025-05-05T22:43:13.099+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:33:02.097910+00:00 [queued]>
[2025-05-05T22:43:13.100+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-05T22:43:13.113+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_to_hdfs> on 2025-05-05 22:33:02.097910+00:00
[2025-05-05T22:43:13.118+0000] {standard_task_runner.py:57} INFO - Started process 531 to run task
[2025-05-05T22:43:13.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'upload_to_hdfs', 'manual__2025-05-05T22:33:02.097910+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmp4b0w58qw']
[2025-05-05T22:43:13.122+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask upload_to_hdfs
[2025-05-05T22:43:13.136+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-05T22:43:13.163+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T22:33:02.097910+00:00 [running]> on host 56aa4ba7abee
[2025-05-05T22:43:13.237+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T22:33:02.097910+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T22:33:02.097910+00:00'
[2025-05-05T22:43:13.238+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 44, in upload_to_hdfs
    webhdfs_hook.create_directory(hdfs_path)
AttributeError: 'WebHDFSHook' object has no attribute 'create_directory'
[2025-05-05T22:43:13.245+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movielens_ingestion, task_id=upload_to_hdfs, execution_date=20250505T223302, start_date=20250505T224313, end_date=20250505T224313
[2025-05-05T22:43:13.256+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task upload_to_hdfs ('WebHDFSHook' object has no attribute 'create_directory'; 531)
[2025-05-05T22:43:13.292+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T22:43:13.317+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
