[2025-05-06T05:15:47.667+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.create_hive_tables manual__2025-05-06T05:10:37.086310+00:00 [queued]>
[2025-05-06T05:15:47.678+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.create_hive_tables manual__2025-05-06T05:10:37.086310+00:00 [queued]>
[2025-05-06T05:15:47.679+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-06T05:15:47.695+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_hive_tables> on 2025-05-06 05:10:37.086310+00:00
[2025-05-06T05:15:47.703+0000] {standard_task_runner.py:57} INFO - Started process 2476 to run task
[2025-05-06T05:15:47.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'create_hive_tables', 'manual__2025-05-06T05:10:37.086310+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmpkr4rdhif']
[2025-05-06T05:15:47.709+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask create_hive_tables
[2025-05-06T05:15:47.726+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T05:15:47.770+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.create_hive_tables manual__2025-05-06T05:10:37.086310+00:00 [running]> on host 7cfed5a894a5
[2025-05-06T05:15:47.873+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='create_hive_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T05:10:37.086310+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T05:10:37.086310+00:00'
[2025-05-06T05:15:47.885+0000] {base.py:73} INFO - Using connection ID 'hiveserver2_default' for task execution.
[2025-05-06T05:15:47.909+0000] {TSocket.py:142} INFO - Could not connect to ('::1', 10000, 0, 0)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 137, in open
    handle.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-06T05:15:47.911+0000] {TSocket.py:142} INFO - Could not connect to ('127.0.0.1', 10000)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 137, in open
    handle.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-06T05:15:47.911+0000] {TSocket.py:145} ERROR - Could not connect to any of [('::1', 10000, 0, 0), ('127.0.0.1', 10000)]
[2025-05-06T05:15:47.912+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 84, in create_hive_tables
    hive_hook.run("""
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/hive/hooks/hive.py", line 869, in get_conn
    return connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyhive/hive.py", line 143, in connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyhive/hive.py", line 269, in __init__
    self._transport.open()
  File "/home/airflow/.local/lib/python3.8/site-packages/thrift_sasl/__init__.py", line 74, in open
    self._trans.open()
  File "/home/airflow/.local/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 146, in open
    raise TTransportException(type=TTransportException.NOT_OPEN, message=msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of [('::1', 10000, 0, 0), ('127.0.0.1', 10000)]
[2025-05-06T05:15:47.925+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movielens_ingestion, task_id=create_hive_tables, execution_date=20250506T051037, start_date=20250506T051547, end_date=20250506T051547
[2025-05-06T05:15:47.940+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task create_hive_tables (Could not connect to any of [('::1', 10000, 0, 0), ('127.0.0.1', 10000)]; 2476)
[2025-05-06T05:15:47.958+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-06T05:15:47.980+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
