[2025-05-06T04:41:43.061+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T01:09:27.363860+00:00 [queued]>
[2025-05-06T04:41:43.078+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T01:09:27.363860+00:00 [queued]>
[2025-05-06T04:41:43.079+0000] {taskinstance.py:1359} INFO - Starting attempt 5 of 6
[2025-05-06T04:41:43.105+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_to_hdfs> on 2025-05-06 01:09:27.363860+00:00
[2025-05-06T04:41:43.116+0000] {standard_task_runner.py:57} INFO - Started process 1443 to run task
[2025-05-06T04:41:43.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'upload_to_hdfs', 'manual__2025-05-06T01:09:27.363860+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmpu0eqrwt2']
[2025-05-06T04:41:43.124+0000] {standard_task_runner.py:85} INFO - Job 73: Subtask upload_to_hdfs
[2025-05-06T04:41:43.154+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T04:41:43.248+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T01:09:27.363860+00:00 [running]> on host 7cfed5a894a5
[2025-05-06T04:41:43.478+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T01:09:27.363860+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T01:09:27.363860+00:00'
[2025-05-06T04:41:44.540+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 70, in upload_to_hdfs
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://e0bd475682a1:9864/webhdfs/v1/user/***/movielens/movies.dat?op=CREATE&user.name=***&namenoderpcaddress=namenode:9000&createflag=&createparent=true&overwrite=true
[2025-05-06T04:41:44.554+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=movielens_ingestion, task_id=upload_to_hdfs, execution_date=20250506T010927, start_date=20250506T044143, end_date=20250506T044144
[2025-05-06T04:41:44.573+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 73 for task upload_to_hdfs (404 Client Error: Not Found for url: http://e0bd475682a1:9864/webhdfs/v1/user/***/movielens/movies.dat?op=CREATE&user.name=***&namenoderpcaddress=namenode:9000&createflag=&createparent=true&overwrite=true; 1443)
[2025-05-06T04:41:44.617+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-06T04:41:44.650+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
