[2025-05-06T04:30:56.669+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T00:05:41.751439+00:00 [queued]>
[2025-05-06T04:30:56.681+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T00:05:41.751439+00:00 [queued]>
[2025-05-06T04:30:56.681+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2025-05-06T04:30:56.702+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_to_hdfs> on 2025-05-06 00:05:41.751439+00:00
[2025-05-06T04:30:56.714+0000] {standard_task_runner.py:57} INFO - Started process 1090 to run task
[2025-05-06T04:30:56.718+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'upload_to_hdfs', 'manual__2025-05-06T00:05:41.751439+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmplyv7o814']
[2025-05-06T04:30:56.722+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask upload_to_hdfs
[2025-05-06T04:30:56.748+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T04:30:56.809+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-06T00:05:41.751439+00:00 [running]> on host 7cfed5a894a5
[2025-05-06T04:30:57.035+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T00:05:41.751439+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T00:05:41.751439+00:00'
[2025-05-06T04:30:57.191+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 69, in upload_to_hdfs
    with open(local_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpb3wpipxe/ml-1m/movies.dat'
[2025-05-06T04:30:57.217+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=movielens_ingestion, task_id=upload_to_hdfs, execution_date=20250506T000541, start_date=20250506T043056, end_date=20250506T043057
[2025-05-06T04:30:57.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task upload_to_hdfs ([Errno 2] No such file or directory: '/tmp/tmpb3wpipxe/ml-1m/movies.dat'; 1090)
[2025-05-06T04:30:57.293+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-06T04:30:57.360+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
