[2025-05-05T23:14:49.475+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T23:14:44.908096+00:00 [queued]>
[2025-05-05T23:14:49.483+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T23:14:44.908096+00:00 [queued]>
[2025-05-05T23:14:49.483+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-05T23:14:49.496+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_to_hdfs> on 2025-05-05 23:14:44.908096+00:00
[2025-05-05T23:14:49.501+0000] {standard_task_runner.py:57} INFO - Started process 1558 to run task
[2025-05-05T23:14:49.503+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movielens_ingestion', 'upload_to_hdfs', 'manual__2025-05-05T23:14:44.908096+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/movielens_ingestion.py', '--cfg-path', '/tmp/tmpfg8kvg08']
[2025-05-05T23:14:49.505+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask upload_to_hdfs
[2025-05-05T23:14:49.518+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-05T23:14:49.545+0000] {task_command.py:415} INFO - Running <TaskInstance: movielens_ingestion.upload_to_hdfs manual__2025-05-05T23:14:44.908096+00:00 [running]> on host 56aa4ba7abee
[2025-05-05T23:14:49.633+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:14:44.908096+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:14:44.908096+00:00'
[2025-05-05T23:14:49.748+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movielens_ingestion.py", line 45, in upload_to_hdfs
    subprocess.run(['docker', 'exec', 'hadoop-cluster_namenode_1', 'hdfs', 'dfs', '-mkdir', '-p', hdfs_path], check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'exec', 'hadoop-cluster_namenode_1', 'hdfs', 'dfs', '-mkdir', '-p', '/user/airflow/movielens']' returned non-zero exit status 1.
[2025-05-05T23:14:49.757+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=movielens_ingestion, task_id=upload_to_hdfs, execution_date=20250505T231444, start_date=20250505T231449, end_date=20250505T231449
[2025-05-05T23:14:49.771+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task upload_to_hdfs (Command '['docker', 'exec', 'hadoop-cluster_namenode_1', 'hdfs', 'dfs', '-mkdir', '-p', '/user/airflow/movielens']' returned non-zero exit status 1.; 1558)
[2025-05-05T23:14:49.795+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T23:14:49.814+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
